# seine - Slim Embedded Images Now Easy
# SPDX-License-Identifier: Apache-2.0

import hashlib
import os
import re
import shutil
import stat
import tempfile
import uuid

import guestfs

from seine                   import pe_cert
from seine                   import utils
from seine.imager.bootloader import detect as detect_bootloader
from seine.imager.appliance import DEVICE
from seine.imager.appliance import ImagerAppliance
from seine.imager.appliance import SCRATCH_DEVICE
from seine.imager.rebuild   import EXT_FSTYPES
from seine.imager.rebuild   import PartitionRebuild
from seine.imager.ostree    import OstreeSysroot
from seine.imager.signers   import BootSigners
from seine.imager.gpt       import GptLayout
from seine.packages          import FALLBACK_EPOCH
from seine.partition        import RO_FSTYPES
from seine.tasks import Task
from seine.extends.uki import ukify_argv
from seine.container import ContainerEngine
from seine.utils            import HOST_ARCH

# squashfs/erofs are not g.mkfs() targets, so RO_FSTYPES mounts are
# staged as this and replaced later (see create()'s finalize pass).
STAGING_TYPE = "ext4"

# Fixed, so the same spec always derives the same GPT/filesystem UUIDs.
UUID_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_DNS, "seine.debian.org")

# Fallback hypervisor per arch, used when cross-building and 'imager:
# hypervisor:' is unset (guestfs would otherwise launch its host-arch qemu).
DEFAULT_HYPERVISORS = {
    "amd64": "/usr/bin/qemu-system-x86_64",
    "arm64": "/usr/bin/qemu-system-aarch64",
    "armhf": "/usr/bin/qemu-system-arm",
    "i386":  "/usr/bin/qemu-system-i386",
}

# libguestfs hardcodes x86-only qemu flags (machine, cpu, console) for any
# hypervisor, with no override for some of them. Confirmed for arm64 only,
# via a real cross-arch build.
CROSS_ARCH_QEMU_FIXUPS = {
    "arm64": {"machine": "virt,accel=tcg", "cpu": "max", "console": "ttyAMA0"},
}

QEMU_WRAPPER_SCRIPT = """#!/bin/bash
# generated by seine -- fixes up qemu flags libguestfs hardcodes for
# x86, then execs the real hypervisor.
args=()
while [ $# -gt 0 ]; do
    case "$1" in
        -global)
            if [ "$2" = "virtio-blk-pci.scsi=off" ]; then
                shift 2
                continue
            fi
            ;;
        -machine)
            args+=("-machine" "{machine}")
            shift 2
            continue
            ;;
        -cpu)
            args+=("-cpu" "{cpu}")
            shift 2
            continue
            ;;
        -append)
            args+=("-append" "${{2/console=ttyS0/console={console}}}")
            shift 2
            continue
            ;;
    esac
    args+=("$1")
    shift
done
exec "{real_hv}" "${{args[@]}}"
"""

from seine.containers.ingest import ContainerdIngestionHandler, DockerIngestionHandler

# Hooks around g.launch()'s real fork(), no-op for CLI builds. The TUI's
# _wire_launch_guard() (seine/tui/target.py) uses these to disconnect and
# reconnect its live mtda connection, whose threads would otherwise stall the fork.
before_launch = lambda: None
after_launch = lambda: None

class Imager(PartitionRebuild, OstreeSysroot, GptLayout, BootSigners):
    def __init__(self, source):
        self.source = source
        # Mount -> where an ostree build mounted it, see _where().
        self._guest_paths = {}
        self.keep = source.options["keep"]
        self.verbose = source.options["verbose"]
        self.reproducible = source.options["reproducible"]
        self._output_dir = None
        self._hypervisor_path = None

    def _mkfs(self, g, part, dev):
        ro = part["type"] in RO_FSTYPES
        fstype = STAGING_TYPE if ro else part["type"]
        label = part.get("label")
        # For FAT this is throwaway: _normalize_fat_tree() redoes it with
        # mtools, which alone pins serial and timestamps. Just enough for
        # grub to have somewhere to write to for now.
        if ro:
            # This staging mount is never rebuilt like root/var are, so
            # its own random htree hash seed would reorder directory
            # entries -- and so the RO image built from it -- every run.
            g.mkfs(fstype, dev, features="^dir_index")
        else:
            g.mkfs(fstype, dev)
        if label:
            g.set_label(dev, label)
        # Not every fstype supports a UUID. Report it if this one fails,
        # instead of hiding it.
        try:
            g.set_uuid(dev, self._uuid_for("fs", label or dev))
        except RuntimeError as e:
            print("  note: could not set a UUID on '%s' (%s): %s" % (dev, fstype, e))
        if self.reproducible and fstype in ("vfat", "msdos"):
            self._pin_fat_serial(g, dev, self._fat_serial(label, dev))


    def _write_fstab(self, g, mount_order, mount_devices, part_index):
        fstab = []
        for m in mount_order:
            # Verity mounts come from systemd-veritysetup-generator + gpt-auto
            # (see _build_verity()), not fstab -- an entry here would mount
            # the raw, unverified partition.
            if m.get("verity"):
                continue
            dev = mount_devices[id(m)]
            ro = m["type"] in RO_FSTYPES
            if m["_lvm"]:
                what = dev
            elif ro and m.get("identify") == "partuuid":
                what = "PARTUUID=%s" % self._partuuid(g, part_index, m)
            elif ro:
                what = "PARTLABEL=%s" % m["label"]
            elif m["type"] in ("vfat", "msdos"):
                if self.reproducible:
                    # Not g.vfs_uuid(dev): fstab is written before the
                    # FAT rebuild that actually sets this serial on
                    # the device.
                    serial = self._fat_serial(m.get("label"), dev)
                    what = "UUID=%s-%s" % (serial[:4], serial[4:])
                else:
                    # No FAT rebuild this run (--reproducible is off):
                    # mkfs.vfat's own serial is what actually lands on
                    # the device, so fstab has to name that instead.
                    what = "UUID=%s" % g.vfs_uuid(dev)
            else:
                what = "UUID=%s" % g.vfs_uuid(dev)
            options = "defaults"
            passno = 2
            if ro:
                options = "ro"
                passno = 0
            elif m["_prefix"] == "/":
                if m["type"] != "btrfs":
                    options = "errors=remount-ro"
                passno = 1
            elif m["type"] == "vfat":
                options = "umask=0077"
            fstab.append("%s %s %s %s 0 %d" % (what, m["_prefix"], m["type"], options, passno))
        g.write("/etc/fstab", ("\n".join(fstab) + "\n").encode())


    def _label_selinux(self, g, mount_order):
        se_contexts = "/etc/selinux/default/contexts/files/file_contexts"
        if not (g.is_file(se_contexts) and g.is_file("/usr/sbin/setfiles")):
            return
        print("Setting file contexts for SELinux...")
        if g.is_file("/etc/default/grub"):
            grub_cfg = g.read_file("/etc/default/grub").decode()
            grub_cfg = re.sub(r'^(GRUB_CMDLINE_LINUX=.*)"$', r'\1 security=selinux"',
                               grub_cfg, flags=re.MULTILINE)
            g.write("/etc/default/grub", grub_cfg.encode())
        # setfiles doesn't cross filesystem boundaries, so run it per mount.
        # Skip FAT, which has no xattr support.
        for m in mount_order:
            if m["type"] in ("vfat", "msdos", "fat", "fat32"):
                continue
            # -v output can be huge and g.sh() ships it back over the
            # guestfsd RPC, which has a size limit. Drop stdout, keep
            # stderr so errors still show up.
            g.sh("setfiles -m%s %s %s >/dev/null" % (
                " -v" if self.verbose else "", se_contexts, m["_prefix"]))

    # 'None' means no kernel -- not every 'multiconfig:' group needs one.
    # More than one kernel/initrd is an error, not a silent pick.
    def _boot_files(self, g):
        entries = g.ls("/boot") if g.is_dir("/boot") else []
        kernels = sorted(e for e in entries if e.startswith("vmlinuz-"))
        initrds = sorted(e for e in entries if e.startswith("initrd.img-"))
        if not kernels and not initrds:
            return None
        if len(kernels) != 1 or len(initrds) != 1:
            raise RuntimeError(
                "expected exactly one kernel and one initrd under '/boot', "
                "found %d kernel(s) and %d initrd(s) (%s)"
                % (len(kernels), len(initrds), ", ".join(entries)))
        return "/boot/%s" % kernels[0], "/boot/%s" % initrds[0]

    # Per-group entries are written directly, not by 'update-grub', so read
    # the cmdline it would otherwise fold into the 'linux' line ourselves.
    def _grub_cmdline(self, g):
        if not g.is_file("/etc/default/grub"):
            return ""
        conf = g.read_file("/etc/default/grub").decode()
        parts = []
        for name in ("GRUB_CMDLINE_LINUX_DEFAULT", "GRUB_CMDLINE_LINUX"):
            m = re.search(r'^%s="(.*)"' % name, conf, re.MULTILINE)
            if m and m.group(1).strip():
                parts.append(m.group(1).strip())
        return " ".join(parts)

    # A GUID/UUID derived from the spec, so a rebuild gets the same one
    # and a changed spec gets a different one. 'parts' picks out which
    # GUID this is (disk, a partition, a filesystem) so none collide.
    def _uuid_for(self, *parts):
        seed = ":".join([self.source.spec_digest()] + list(parts))
        return str(uuid.uuid5(UUID_NAMESPACE, seed))


    # Runs before 'hp's partition is written -- the root hash decides both
    # GUIDs. squashfs (unlike erofs) doesn't pad to veritysetup's 4096-byte
    # blocks, so pad here.
    def _build_verity(self, g, tools_dir, work_dir, m, scratch, hp, part_index):
        print("Building verity hash tree for '%s'..." % m["label"])
        block_size = 4096
        size = g.filesize(scratch)
        aligned = -(-size // block_size) * block_size
        if aligned != size:
            g.truncate_size(scratch, aligned)

        run = "LD_LIBRARY_PATH=%s %s/veritysetup" % (tools_dir, tools_dir)
        hash_scratch = "%s/%s.verity.img" % (work_dir, hp["label"])
        roothash_file = "%s/%s.roothash" % (work_dir, hp["label"])
        # Without these, verity picks a random salt and UUID each build,
        # so even identical content gets a different root hash every time.
        salt = hashlib.sha256(
            ("verity-salt:%s" % self._uuid_for("verity-salt", m["label"])).encode()
        ).hexdigest()
        g.sh("%s format --root-hash-file=%s --salt=%s --uuid=%s %s %s"
             % (run, roothash_file, salt, self._uuid_for("verity-uuid", m["label"]),
                scratch, hash_scratch))
        roothash = g.read_file(roothash_file).decode().strip()
        g.rm(roothash_file)
        if len(roothash) != 64:
            raise RuntimeError(
                "'veritysetup format' for '%s' produced a %d-hex-digit root "
                "hash, expected 64 (sha256) -- only the default hash "
                "algorithm is supported" % (m["label"], len(roothash)))

        data_guid = self._hex_to_gpt_guid(roothash[0:32])
        hash_guid = self._hex_to_gpt_guid(roothash[32:64])
        g.part_set_gpt_guid(DEVICE, part_index[id(m)], data_guid)
        g.part_set_gpt_guid(DEVICE, part_index[id(hp)], hash_guid)

        built = g.filesize(hash_scratch)
        cap = (hp["_end_mib"] - hp["_start_mib"]) * 1024 * 1024
        if built > cap:
            raise RuntimeError(
                "built verity hash tree for '%s' is %d bytes, larger than "
                "its %d-byte partition '%s'"
                % (m["label"], built, cap, hp["label"]))
        g.copy_file_to_device(
            hash_scratch, DEVICE, destoffset=hp["_start_mib"] * 1024 * 1024)
        g.rm(hash_scratch)
        return roothash


    # gpt-auto-generator refuses an unanchored verity pair, so 'usrhash='
    # must be added for '/usr' to mount. Signed only if 'image: secure-boot:'
    # is set. Runs while 'm' and siblings are still mounted.
    def _anchor_uki(self, g, mounts, mounted, m, roothash):
        if m["_prefix"] != "/usr/":
            return
        efi_dirs = []
        for other in mounts:
            if id(other) not in mounted:
                continue
            efi_dir = "%s/EFI/Linux" % other["_prefix"].rstrip("/")
            if g.is_dir(efi_dir):
                efi_dirs.append(efi_dir)

        for efi_dir in efi_dirs:
            for name in sorted(g.ls(efi_dir)):
                if name.endswith(".efi"):
                    self._anchor_one_uki(g, efi_dir, name, roothash)


    # objcopy/ukify/sbsign run as container commands, not inside the
    # appliance, on a copy of the '.efi' downloaded to a scratch dir.
    def _anchor_one_uki(self, g, efi_dir, name, roothash):
        print("Anchoring '%s' with usrhash=%s..." % (name, roothash))
        efi_path = "%s/%s" % (efi_dir, name)
        workdir = tempfile.mkdtemp(dir=self._output_dir, prefix="uki-anchor-")
        original = os.path.join(workdir, "original.efi")
        g.download(efi_path, original)

        # ukify stamps the PE header's build time from this unless told
        # otherwise, which would make the .efi differ build to build.
        epoch = self.source._epoch()

        def run(args):
            ContainerEngine.run(
                ["container", "run", "--rm", "-v", "%s:/work" % workdir,
                 "-e", "SOURCE_DATE_EPOCH=%d" % epoch,
                 "-w", "/work", self._extra_tools.name] + args, check=True)

        # One objcopy dumps all three sections byte-identical to build time.
        # '/dev/null' as output makes objcopy exit 1 despite success, so use
        # a throwaway file instead.
        run(["objcopy",
             "--dump-section", ".linux=linux.bin",
             "--dump-section", ".initrd=initrd.bin",
             "--dump-section", ".cmdline=cmdline.txt",
             "original.efi", "discard.efi"])

        base_cmdline = open(os.path.join(workdir, "cmdline.txt")).read().strip()
        cmdline = ("%s usrhash=%s" % (base_cmdline, roothash)) if base_cmdline \
            else "usrhash=%s" % roothash

        # A real 'ukify build', not an 'objcopy --update-section' patch, so
        # a future PCR-policy pass only extends 'extra' here instead of a
        # second code path.
        run(ukify_argv("linux.bin", "initrd.bin", cmdline, "rebuilt.efi"))
        # ukify stamps the PE header with the real build time regardless
        # of SOURCE_DATE_EPOCH -- pin it directly, before signing folds
        # it into the signature.
        self._pin_pe_timestamp(os.path.join(workdir, "rebuilt.efi"), epoch)

        secure_boot = self.source.partitionHandler.secure_boot
        result = "rebuilt.efi"
        if secure_boot is not None:
            result = self._sign_uki(workdir, epoch)

        g.upload(os.path.join(workdir, result), efi_path)
        # g.upload() stamps the real time, unlike the mtools rebuild
        # the rest of this FAT tree already went through.
        g.utimens(efi_path, epoch, 0, epoch, 0)

        # The cmdline change invalidates whatever _scan_boot_signers()
        # recorded before anchoring -- replace it with the truth.
        with open(os.path.join(workdir, result), "rb") as f:
            self._boot_signers[efi_path] = pe_cert.extract_signer_cert(f.read())


    # Deepest mount first, so a mount's children are already unmounted
    # (empty dir, not live content) when read. 'mounts' is one group's
    # list -- create() handles groups one at a time.
    def _build_ro_images(self, g, mounts, mount_devices, part_index, hash_part_for):
        built_sizes = {}
        ro_mounts = [m for m in mounts if m["type"] in RO_FSTYPES]
        if not ro_mounts:
            return built_sizes

        mounted = {id(m) for m in mounts}
        # A rebuilt ext2/3/4 root goes read-only by now -- use '/mnt'
        # instead, a normal FHS directory that survives root's rebuild
        # (SCRATCH_MOUNT itself does not).
        root_m = next((mnt for mnt in mounts if mnt["_prefix"] == "/"), None)
        root_ro = root_m is not None and root_m["type"] in EXT_FSTYPES
        work_dir = ""
        if root_ro:
            work_dir = "/mnt"
            g.mount(SCRATCH_DEVICE, work_dir)
        tools_dir = self._upload_tools(
            g, "%s/.imager-extra-tools" % work_dir, self._extra_tools_files)

        for m in sorted(ro_mounts, key=lambda m: m["_depth"], reverse=True):
            print("Building %s image for '%s'..." % (m["type"], m["label"]))
            for child in mounts:
                if child is not m and id(child) in mounted \
                   and child["_prefix"].startswith(m["_prefix"]):
                    g.umount(child["_prefix"])
                    mounted.discard(id(child))

            tool = "%s/%s" % (tools_dir,
                "mksquashfs" if m["type"] == "squashfs" else "mkfs.erofs")
            run = "LD_LIBRARY_PATH=%s %s" % (tools_dir, tool)

            scratch = "%s/%s.img" % (work_dir, m["label"])
            comp = m.get("compression")
            # Fixed timestamp, not real mtimes: same content must give the
            # same bytes (and verity hash) across rebuilds.
            if m["type"] == "squashfs":
                # '-processors 1': parallel compression can place blocks
                # and fragments in a different order every run, even for
                # identical content.
                g.sh("%s %s %s -noappend -all-time %d -processors 1%s" % (
                    run, m["_prefix"], scratch, FALLBACK_EPOCH,
                    " -comp %s" % comp if comp else ""))
            else:
                # mkfs.erofs takes output before source, the reverse of
                # mksquashfs. '-U' pins the volume UUID -- otherwise
                # random, so /usr's own bytes would never repeat.
                g.sh("%s%s -T%d -U %s %s %s" % (
                    run, " -z%s" % comp if comp else "", FALLBACK_EPOCH,
                    self._uuid_for("erofs", m["label"]), scratch, m["_prefix"]))

            built = g.filesize(scratch)
            built_sizes[id(m)] = built

            # Still while 'm' is mounted: g.sh() chroots via '/bin/sh' at
            # '/', a symlink into '/usr' on usrmerged targets -- unmount
            # first and g.sh() has nothing to run.
            hp = hash_part_for.get(m["label"])
            if hp is not None:
                roothash = self._build_verity(
                    g, tools_dir, work_dir, m, scratch, hp, part_index)
                self._anchor_uki(g, mounts, mounted, m, roothash)

            g.umount(m["_prefix"])
            mounted.discard(id(m))

            if m["_lvm"]:
                dest, offset, cap = mount_devices[id(m)], 0, m["size"]
            else:
                dest, offset = DEVICE, m["_start_mib"] * 1024 * 1024
                cap = (m["_end_mib"] - m["_start_mib"]) * 1024 * 1024
            if built > cap:
                raise RuntimeError(
                    "built %s image for '%s' is %d bytes, larger than its "
                    "%d-byte partition/volume" % (m["type"], m["label"], built, cap))

            # The old ext4 staging filesystem's superblock and journal
            # still sit past 'built', with real timestamps. Pad first so
            # the copy below overwrites the whole partition/volume.
            if built < cap:
                g.truncate_size(scratch, cap)

            g.copy_file_to_device(scratch, dest, destoffset=offset)
            g.rm(scratch)

        g.rm_rf(tools_dir)
        if root_ro:
            g.umount(work_dir)
        return built_sizes

    def _hypervisor(self, target_arch):
        imager_spec = self.source.spec.get("imager") or {}
        return imager_spec.get("hypervisor") or DEFAULT_HYPERVISORS.get(target_arch)

    # Writes a qemu wrapper fixing libguestfs's hardcoded x86 flags for
    # 'target_arch', and returns its path for g.set_hv().
    def _write_qemu_wrapper(self, output_dir, target_arch, real_hv):
        fixups = CROSS_ARCH_QEMU_FIXUPS.get(target_arch)
        if fixups is None:
            raise NotImplementedError(
                "cross-building for architecture '%s' is not yet supported "
                "(no verified qemu launch fixups)" % target_arch)
        wrapper_path = os.path.join(output_dir, "qemu-wrapper.sh")
        with open(wrapper_path, "w") as f:
            f.write(QEMU_WRAPPER_SCRIPT.format(real_hv=real_hv, **fixups))
        os.chmod(wrapper_path, os.stat(wrapper_path).st_mode | stat.S_IEXEC)
        return wrapper_path

    # Every architecture now builds and boots the same custom appliance.
    # Cross-arch builds additionally need a qemu wrapper for its
    # hardcoded x86 flags.
    def _prepare_appliance(self, output_dir):
        target_arch = self.source.spec["distribution"]["architecture"]
        print("Preparing imager appliance...")
        imagerAppliance = ImagerAppliance(self.source)
        imagerAppliance.create()
        appliance_dir, extra_tools_files = imagerAppliance.extract(output_dir)
        os.environ["LIBGUESTFS_PATH"] = appliance_dir
        # Used later by _anchor_one_uki()'s objcopy/ukify/sbsign steps.
        self._extra_tools = imagerAppliance
        self._extra_tools_files = extra_tools_files

        real_hv = self._hypervisor(target_arch)
        if target_arch == HOST_ARCH:
            return real_hv
        os.environ["LIBGUESTFS_BACKEND_SETTINGS"] = "force_tcg"
        return self._write_qemu_wrapper(output_dir, target_arch, real_hv)

    # Two separate tasks: the appliance only needs packages (for its own
    # kernel) and the target bootstrap, not the built root file-system --
    # combining them would wait on the disk unnecessarily.
    def tasks(self, needs_packages="packages"):
        return [
            Task("appliance", self._prepare,
                 needs=["bootstrap-target", needs_packages]),
            Task("image", self._build, needs=["disk", "appliance"]),
        ]

    def _prepare(self):
        if self.source._image_current():
            return
        # Scratch dir for the unpacked appliance/tools, not kept.
        self._output_dir = tempfile.mkdtemp(dir=ContainerEngine.scratch(),
                                           prefix="imager-")
        self._hypervisor_path = self._prepare_appliance(self._output_dir)

    def _build(self):
        digest = self.source._image_digest()
        if self.source._image_current(digest):
            print(f"disk image up to date ({utils.display_path(self.source._output)})")
            return
        self.create()
        utils.invalidate_digest_file(self.source._image_digest_file())
        os.rename(self.source._image, self.source._output)
        self.source._image = None
        recipe = getattr(self.source, "_image_recipe", lambda: None)()
        utils.write_digest_file(self.source._image_digest_file(), digest, recipe=recipe)

    def create(self):
        ph = self.source.partitionHandler
        disk = self.source._image
        output_dir = self._output_dir
        # Path -> cert (or None if unsigned), across every multiconfig
        # group -- one boot-chain recap for the whole disk.
        self._boot_signers = {}
        try:
            hypervisor = self._hypervisor_path

            print("Starting imager appliance...")
            g = guestfs.GuestFS(python_return_dict=True)
            imagerAppliance = ImagerAppliance(self.source)
            if imagerAppliance.memsize():
                g.set_memsize(imagerAppliance.memsize())
            g.add_drive_opts(disk, format="raw", readonly=False)
            # Grouped by 'source': 'None' is a spec with no 'multiconfig:'
            # groups. Declared groups are side-by-side, non-overlapping
            # OSes, mounted and unmounted one at a time.
            by_source = {}
            for m in ph.mounts:
                by_source.setdefault(m.get("source"), []).append(m)
            declared_groups = sorted(name for name in by_source if name is not None)
            sources = ([None] if None in by_source else []) + declared_groups

            # Boot owner goes last: its iteration writes every group's
            # grub.cfg entry, so all other kernels/initrds must be known first.
            boot_owner = (self.source.spec.get("imager") or {}).get("boot") or "main"
            if declared_groups:
                if boot_owner not in declared_groups:
                    raise RuntimeError(
                        "'imager: boot: %s' is not one of the declared "
                        "'multiconfig:' groups (%s)"
                        % (boot_owner, ", ".join(declared_groups)))
                sources = [s for s in sources if s != boot_owner] + [boot_owner]

            rooted = [s for s in sources if any(m["_prefix"] == "/" for m in by_source[s])]
            if len({ph.ostree_for(s)["mode"] != "disabled" for s in rooted}) > 1:
                raise NotImplementedError(
                    "one disk cannot yet boot both ostree and plain root "
                    "file-systems: set 'image: ostree: sources' to the same "
                    "mode for every group")

            source_archives = {}
            all_container_archives = []
            containers_fetch_dir = os.path.join(
                self.source.options.get("build_dir") or "build", "containers")

            for s in sources:
                containers_list = self.source.containers if s is None else \
                    getattr(self.source.subbuilds[s].image, "containers", [])
                distro = self.source.spec["distribution"] if s is None else \
                    self.source.subbuilds[s].spec["distribution"]
                files = self.source.options.get("files") or [] if s is None else \
                    self.source.subbuilds[s].options.get("files") or []
                spec_dir = os.path.dirname(files[0]) if len(files) > 0 else "."
                src_list = []
                for c in containers_list:
                    arch_path = c.archive_for(distro["architecture"], spec_dir=spec_dir)
                    if arch_path and os.path.exists(arch_path):
                        pass
                    elif c.image:
                        # Not vendored — fetch from the registry now.
                        print("  fetching container %s (%s)..." % (c.image, distro["architecture"]))
                        arch_path = c.fetch_archive(distro["architecture"], containers_fetch_dir)
                    else:
                        raise FileNotFoundError("container archive '%s' not found" % arch_path)
                    if arch_path not in all_container_archives:
                        all_container_archives.append(arch_path)
                    src_list.append((
                        arch_path,
                        getattr(c, "target", "docker"),
                        getattr(c, "root", "/var/lib/docker"),
                        getattr(c, "namespace", None),
                        c.image or getattr(c, "file", None) or os.path.basename(arch_path),
                    ))
                source_archives[s] = src_list

            need_ext = any(m["type"] in EXT_FSTYPES for m in ph.mounts)
            need_fat = any(m["type"] in ("vfat", "msdos") for m in ph.mounts)
            if need_ext or need_fat:
                sizes = []
                if need_ext:
                    ext_mounts = [m for m in ph.mounts if m["type"] in EXT_FSTYPES]
                    # Room for one mount's captured content plus its rebuilt
                    # image at once -- never more than twice its own biggest
                    # partition, plus a little slack for filesystem overhead.
                    largest = max(m["_size"] for m in ext_mounts)
                    sizes.append(2 * largest + 128 * 1024 * 1024)
                if need_fat:
                    # Room for the biggest FAT partition's own copy plus
                    # the mtools, staged for its rebuild (see
                    # _normalize_fat_tree()).
                    largest_fat = max(m["_size"] for m in ph.mounts
                                      if m["type"] in ("vfat", "msdos"))
                    sizes.append(largest_fat + 128 * 1024 * 1024)
                # Shared one source at a time, so the biggest single need
                # covers every rebuild.
                scratch_size = max(sizes)
                scratch_disk = os.path.join(output_dir, "ext-scratch.raw")
                with open(scratch_disk, "wb") as f:
                    f.truncate(scratch_size)
                g.add_drive_opts(scratch_disk, format="raw", readonly=False)

            # Staged rootfs of an ostree build, sized like the sysroot
            # partition that will hold it (sparse, so cheap).
            stage_sizes = [m["_size"] for m in ph.mounts if m["_prefix"] == "/"
                           and ph.ostree_for(m.get("source"))["mode"] != "disabled"]
            if stage_sizes:
                stage_disk = os.path.join(output_dir, "ostree-stage.raw")
                with open(stage_disk, "wb") as f:
                    f.truncate(max(stage_sizes) + 128 * 1024 * 1024)
                g.add_drive_opts(stage_disk, format="raw", readonly=False)

            archive_to_guest_path = {}
            if all_container_archives:
                containers_stage_dir = os.path.join(output_dir, "containers")
                os.makedirs(containers_stage_dir, exist_ok=True)
                for idx, arch in enumerate(all_container_archives):
                    staged_name = "archive_%04d.tar" % idx
                    staged_link = os.path.join(containers_stage_dir, staged_name)
                    if not os.path.exists(staged_link):
                        try:
                            os.link(os.path.abspath(arch), staged_link)
                        except OSError:
                            shutil.copyfile(os.path.abspath(arch), staged_link)
                    archive_to_guest_path[arch] = "/run/containers/%s" % staged_name

                g.config(
                    "-virtfs",
                    "local,path=%s,mount_tag=seine_containers,security_model=none,readonly=on"
                    % containers_stage_dir,
                )

            if hypervisor:
                if self.verbose:
                    print("  hypervisor: %s" % hypervisor)
                g.set_hv(hypervisor)
            if ph.groups:
                # pvcreate/vgcreate/lvcreate stamp wall-clock time and a
                # random UUID into their metadata; the appliance's wrapper
                # (imager/appliance.py) freezes the time and pins the UUIDs.
                g.set_append("faketime=%d seed=%s" % (
                    self.source._epoch(), self.source.spec_digest()))
            # Wraps the whole session, not just g.launch(): libguestfs forks
            # again on g.shutdown()/g.close(), which hangs if left unguarded.
            before_launch()
            try:
                g.launch()
                if need_ext or need_fat:
                    # No htree hashing: its read order uses a random per-build
                    # seed, silently reordering mke2fs -d's layout for this
                    # rebuild or the FAT staging area below.
                    g.mkfs("ext4", SCRATCH_DEVICE, features="^dir_index")

                part_devices, part_index, hash_part_for = self._create_partitions(g, ph)
                vol_devices = self._create_volumes(g, ph, part_devices)

                boot_entries = []
                for source in sources:
                    mounts = sorted(by_source[source], key=lambda m: m["_depth"])
                    container_devs = [
                        (archive_to_guest_path[arch_path], target, root, ns, img_name)
                        for (arch_path, target, root, ns, img_name) in source_archives.get(source, [])
                    ]
                    if ph.ostree_for(source)["mode"] != "disabled" \
                            and any(m["_prefix"] == "/" for m in mounts):
                        mount_devices = self._deploy_ostree(
                            g, ph, source, mounts, part_devices, vol_devices,
                            part_index, container_devs, boot_owner, boot_entries)
                        g.umount_all()
                        self._guest_paths = {}
                        if self.reproducible:
                            self._pin_ext_mtimes(g, mounts, mount_devices)
                        continue
                    mount_devices = self._populate_source(
                        g, ph, source, mounts, part_devices, vol_devices, part_index,
                        container_devices=container_devs)
                    self._install_boot_entry(
                        g, part_index, source, mounts, boot_owner, boot_entries)
                    self._normalize_mount_timestamps(g, mounts, mount_devices)
                    self._scan_boot_signers(g, mounts)
                    built_sizes = self._build_ro_images(
                        g, mounts, mount_devices, part_index, hash_part_for)
                    self._print_disk_usage(g, ph, mounts, built_sizes)
                    g.umount_all()
                    if self.reproducible:
                        self._pin_ext_mtimes(g, mounts, mount_devices)

                g.shutdown()
                g.close()
                self._report_boot_signers()
                print("Done.")
            finally:
                after_launch()
        finally:
            if self.keep:
                print("keeping '%s' (imager kernel files) as requested" % output_dir)
            else:
                shutil.rmtree(output_dir, ignore_errors=True)


    def _populate_source(self, g, ph, source, mounts, part_devices, vol_devices, part_index,
                         container_devices=None):
        print("Mounting %s file-systems..."
              % (("'%s'" % source) if source else "the image's own"))
        mount_devices = {}
        for m in mounts:
            dev = part_devices.get(id(m)) or vol_devices.get(id(m))
            mount_devices[id(m)] = dev
            if m["_prefix"] != "/":
                prefix = m["_prefix"].rstrip("/")
                parent = os.path.dirname(prefix)
                if parent and parent != "/":
                    g.mkdir_p(parent)
                g.mkmountpoint(prefix)
            g.mount(dev, m["_prefix"])

        print("Extracting root file-system...")
        tarball = self.source._tarball_for(source)
        # xattrs=True restores file capabilities and the like from the
        # tarball's PAX headers.
        g.tar_in_opts(tarball, "/", xattrs=True)

        print("Writing fstab...")
        self._write_fstab(g, mounts, mount_devices, part_index)

        if source is None:
            print("Copying bootlets...")
            for bootlet in ph.bootlets:
                data = g.read_file(bootlet["file"])
                g.pwrite_device(DEVICE, data, bootlet["_seek"] * 1024)

        if container_devices:
            self._ingest_containers(g, container_devices)

        self._label_selinux(g, mounts)
        return mount_devices


    # Ingests preloaded containers into their respective runtime storage inside the appliance,
    # then prunes daemon state and clamps mtimes for reproducibility.
    def _ingest_containers(self, g, container_devices):
        epoch = self.source._epoch()
        normalized = []
        for entry in container_devices:
            if isinstance(entry, tuple):
                if len(entry) == 5:
                    dev, target, root, ns, img_name = entry
                elif len(entry) == 4:
                    dev, target, root, ns = entry
                    img_name = os.path.basename(dev)
                else:
                    dev = entry[0]
                    target, root, ns, img_name = "docker", "/var/lib/docker", None, os.path.basename(dev)
                normalized.append((dev, target or "docker", root or "/var/lib/docker", ns, img_name))
            else:
                normalized.append((entry, "docker", "/var/lib/docker", None, os.path.basename(entry)))

        groups = {}
        for dev, target, root, ns, img_name in normalized:
            key = (target, root, ns)
            if key not in groups:
                groups[key] = []
            groups[key].append((dev, img_name))

        for (target, root, ns), items in groups.items():
            if target == "containerd":
                print("Preloading containerd images inside appliance (%s, namespace %s)..."
                      % (root, ns or "default"))
                handler = ContainerdIngestionHandler(root=root, namespace=ns or "default")
            else:
                print("Preloading Docker containers inside appliance (%s)..." % root)
                handler = DockerIngestionHandler(root=root)

            g.debug("sh", [handler.generate_start_script(epoch)])
            try:
                for dev, img_name in items:
                    print("  preloading container %s..." % img_name)
                    g.debug("sh", [handler.generate_import_script(dev, epoch)])
            finally:
                if getattr(self, "reproducible", False):
                    print("  normalizing %s container storage (%s)..." % (target, root))
                g.debug("sh", [handler.generate_stop_script(epoch)])

    # 'update-grub' embeds the root LV's random LVM UUIDs as a boot
    # search hint. Safe to fake: it only speeds up the search, actual
    # booting still goes by our own fixed filesystem UUID.
    def _normalize_grub_lvmid(self, g):
        path = "/boot/grub/grub.cfg"
        if not g.is_file(path):
            return
        def fake_uuid(seed):
            h = self._uuid_for(seed).replace("-", "")
            return "-".join([h[0:6], h[6:10], h[10:14], h[14:18], h[18:22], h[22:26], h[26:32]])
        cfg = g.read_file(path).decode()
        cfg = re.sub(r"lvmid/[\w-]+/[\w-]+",
                     "lvmid/%s/%s" % (fake_uuid("grub-lvmid-vg"), fake_uuid("grub-lvmid-lv")), cfg)
        g.write(path, cfg.encode())

    def _install_boot_entry(self, g, part_index, source, mounts, boot_owner, boot_entries):
        # source is None: plain single update-grub call. A declared group
        # instead records its boot info; the boot owner (last) writes every
        # group's menuentry, itself first as the static default.
        root_m = next((m for m in mounts if m["_prefix"] == "/"), None)
        if root_m is not None and source is None:
            bootloader = detect_bootloader(g, DEVICE)
            if bootloader:
                print("Installing boot loader and entries...")
                bootloader.install(g, "/efi")
                bootloader.add_entry(g)
                self._normalize_grub_lvmid(g)
                self._sign_bootloader_files(g, bootloader, "/efi")
        elif root_m is not None:
            boot_files = self._boot_files(g)
            if boot_files is not None:
                if id(root_m) not in part_index:
                    raise RuntimeError(
                        "'multiconfig:' group '%s' has an LVM root -- "
                        "a per-group GRUB boot entry needs a GPT "
                        "partition, not a logical volume" % source)
                kernel, initrd = boot_files
                boot_entries.append({
                    "label": source,
                    "kernel": kernel,
                    "initrd": initrd,
                    "root_partuuid": self._partuuid(g, part_index, root_m),
                    "root_label": root_m["label"],
                    "cmdline": self._grub_cmdline(g),
                })
            if source == boot_owner:
                bootloader = detect_bootloader(g, DEVICE)
                if bootloader:
                    print("Installing boot loader and entries...")
                    bootloader.install(g, "/efi", boot_directory="/efi")
                    ordered = [e for e in boot_entries if e["label"] == boot_owner] + \
                        [e for e in boot_entries if e["label"] != boot_owner]
                    for entry in ordered:
                        bootloader.add_entry(
                            g, group_label=entry["label"],
                            kernel=entry["kernel"], initrd=entry["initrd"],
                            root_partuuid=entry["root_partuuid"],
                            root_label=entry["root_label"],
                            cmdline=entry["cmdline"])
                    self._sign_bootloader_files(g, bootloader, "/efi")


    def _print_disk_usage(self, g, ph, mounts, built_sizes):
        print("Disk usage:")
        for m in mounts:
            if m["type"] in RO_FSTYPES:
                print("%s\t%s (%s)" % (
                    m["_prefix"], ph._to_human_size(built_sizes[id(m)]), m["type"]))
                continue
            st = g.statvfs(m["_prefix"])
            total = st["blocks"] * st["frsize"]
            used = total - st["bfree"] * st["frsize"]
            print("%s\t%s used / %s total" % (
                m["_prefix"], ph._to_human_size(used), ph._to_human_size(total)))
