# seine - Slim Embedded Images Now Easy
# SPDX-License-Identifier: Apache-2.0

# For 'extends: go: license-scan: true': turns a syft scan of the whole
# build tree into SBOM components and DEP-5 copyright stanzas, for the
# app itself and for each of its vendored modules.

import os
import re

from seine import sbom

MODULE_RE = re.compile(r"^# (\S+) (\S+)")
MODULE_LINE_RE = re.compile(r"^module\s+(\S+)")

MARKER = ("# --- Auto-generated by seine from vendored Go modules. "
          "Review before release. ---")

# Without '--enrich golang', syft never reads a vendored module's
# LICENSE file: every license comes back NOASSERTION regardless.
def scan_tree(build_dir):
    return sbom.scan_directory(build_dir, extra_args=["--enrich", "golang"])

# vendor/modules.txt lines look like '# <module> <version>'; package
# lines underneath are indented and have no leading '#'.
def parse_modules_txt(vendor_dir):
    modules = []
    with open(os.path.join(vendor_dir, "modules.txt")) as f:
        for line in f:
            match = MODULE_RE.match(line)
            if match:
                modules.append((match.group(1), match.group(2)))
    return modules

# go.mod's first 'module <path>' line, the app's own module path -- used
# to find its package among syft's, the same way a vendored one is found.
def parse_module_path(build_dir):
    with open(os.path.join(build_dir, "go.mod")) as f:
        for line in f:
            match = MODULE_LINE_RE.match(line)
            if match:
                return match.group(1)
    return None

def _purl_path(package):
    for ref in package.get("externalRefs", []):
        if ref.get("referenceType") == "purl":
            locator = ref.get("referenceLocator", "")
            return locator.split("pkg:golang/", 1)[-1].split("@", 1)[0]
    return None

def _license_of(package):
    license = package.get("licenseConcluded") or package.get("licenseDeclared")
    return None if license in (None, "NOASSERTION", "NONE") else license

def _copyright_of(package):
    text = package.get("copyrightText")
    return None if text in (None, "NOASSERTION", "NONE") else text

def _by_purl_path(syft_doc):
    by_path = {}
    for package in syft_doc.get("packages", []):
        path = _purl_path(package)
        if path:
            by_path[path] = package
    return by_path

# A single 'Files:'/'Copyright:'/'License:' stanza for 'module_path'.
# Nothing found for it gets 'License: NOASSERTION' and a build warning,
# for the packager to review.
def _stanza(files_pattern, module_path, by_path):
    package = by_path.get(module_path)
    license = _license_of(package) if package else None
    copyright = _copyright_of(package) if package else None
    if license is None:
        print(f"go: no license found for '{module_path}', marking "
              f"'{files_pattern}' NOASSERTION for review")
    return (f"Files: {files_pattern}\n"
            f"Copyright: {copyright or 'see ' + files_pattern}\n"
            f"License: {license or 'NOASSERTION'}\n")

def license_stanzas(modules, syft_doc):
    by_path = _by_purl_path(syft_doc)
    return "\n".join(_stanza(f"vendor/{path}/*", path, by_path)
                     for path, _version in modules)

# The app's own top-level stanza, from its own module path in 'go.mod'
# (not one seine invents): 'None' if go.mod has no 'module' line.
def main_stanza(module_path, syft_doc):
    return _stanza("*", module_path, _by_purl_path(syft_doc))
